// lib/mock-data.ts

export const mockLanguages = [
  { code: "en", name: "English", native: "English" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
];

export const mockChannels = [
  { id: "ch1", slug: "islamic-guidance", name: "Islamic Guidance", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 1200000, videosCount: 450, verified: true, language: "en", description: "Authentic Islamic teachings from the Quran and Sunnah.", website: "islamicguidance.com", facebook: "fb.com/islamicguidance", twitter: "twitter.com/islamicguidance", youtube: "youtube.com/islamicguidance" },
  { id: "ch2", slug: "daily-dawah", name: "Daily Dawah", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 780000, videosCount: 320, verified: false, language: "en", description: "Daily reminders and Dawah content.", website: "dailydawah.com", facebook: "fb.com/dailydawah", twitter: "twitter.com/dailydawah", youtube: "youtube.com/dailydawah" },
  { id: "ch3", slug: "merciful-servant", name: "Merciful Servant", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 2000000, videosCount: 600, verified: true, language: "en", description: "Spiritual reminders and Islamic lectures.", website: "mercifulservant.com", facebook: "fb.com/mercifulservant", twitter: "twitter.com/mercifulservant", youtube: "youtube.com/mercifulservant" },
  { id: "ch4", slug: "digital-mimbar", name: "Digital Mimbar", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 500000, videosCount: 280, verified: false, language: "en", description: "Islamic lectures and talks.", website: "digitalmimbar.com", facebook: "fb.com/digitalmimbar", twitter: "twitter.com/digitalmimbar", youtube: "youtube.com/digitalmimbar" },
  { id: "ch5", slug: "huda-tv", name: "Huda TV", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 350000, videosCount: 190, verified: false, language: "en", description: "Family and lifestyle Islamic content.", website: "hudatv.com", facebook: "fb.com/hudatv", twitter: "twitter.com/hudatv", youtube: "youtube.com/hudatv" },
  { id: "ch6", slug: "peace-tv", name: "Peace TV", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 450000, videosCount: 210, verified: true, language: "en", description: "Islamic lectures and debates.", website: "peacetv.com", facebook: "fb.com/peacetv", twitter: "twitter.com/peacetv", youtube: "youtube.com/peacetv" },
  { id: "ch7", slug: "one-islam", name: "One Islam Productions", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 800000, videosCount: 400, verified: true, language: "en", description: "High-quality Islamic media content.", website: "oneislam.com", facebook: "fb.com/oneislam", twitter: "twitter.com/oneislam", youtube: "youtube.com/oneislam" },
  { id: "ch8", slug: "the-deen-show", name: "The Deen Show", avatar: "/placeholder.svg?height=48&width=48", cover: "/placeholder.svg?height=300&width=1200", subscribers: 250000, videosCount: 150, verified: false, language: "en", description: "Engaging discussions on Islam.", website: "thedeenshow.com", facebook: "fb.com/thedeenshow", twitter: "twitter.com/thedeenshow", youtube: "youtube.com/thedeenshow" },
];

export const mockScholars = [
  { id: "s1", slug: "abdul-alim", name: "Sheikh Abdul Alim", designation: "Islamic Scholar", image: "/placeholder.svg?height=96&width=96", languages: ["en", "ar", "bn"], description: "Sheikh Abdul Alim is a renowned Islamic scholar known for his deep knowledge of Quran and Hadith.", website: "abdulalim.com", facebook: "fb.com/abdulalim", twitter: "twitter.com/abdulalim", youtube: "youtube.com/abdulalim" },
  { id: "s2", slug: "bilal-philips", name: "Dr. Bilal Philips", designation: "Islamic Preacher & Author", image: "/placeholder.svg?height=96&width=96", languages: ["en"], description: "Dr. Bilal Philips is a Jamaican-born Canadian Islamic scholar, teacher, speaker, and author.", website: "bilalphilips.com", facebook: "fb.com/bilalphilips", twitter: "twitter.com/bilalphilips", youtube: "youtube.com/bilalphilips" },
  { id: "s3", slug: "mufti-menk", name: "Mufti Menk", designation: "Grand Mufti", image: "/placeholder.svg?height=96&width=96", languages: ["en", "ur"], description: "Mufti Menk is a Zimbabwean Islamic scholar and Grand Mufti.", website: "muftimenk.com", facebook: "fb.com/muftimenk", twitter: "twitter.com/muftimenk", youtube: "youtube.com/muftimenk" },
  { id: "s4", slug: "yasir-qadhi", name: "Sheikh Yasir Qadhi", designation: "Islamic Scholar", image: "/placeholder.svg?height=96&width=96", languages: ["en"], description: "Sheikh Yasir Qadhi is a prominent American Islamic scholar.", website: "yasirqadhi.com", facebook: "fb.com/yasirqadhi", twitter: "twitter.com/yasirqadhi", youtube: "youtube.com/yasirqadhi" },
  { id: "s5", slug: "nouman-ali-khan", name: "Nouman Ali Khan", designation: "Quran Instructor", image: "/placeholder.svg?height=96&width=96", languages: ["en"], description: "Nouman Ali Khan is the founder of Bayyinah Institute and a renowned Quran instructor.", website: "bayyinah.com", facebook: "fb.com/noumanalikhan", twitter: "twitter.com/noumanalikhan", youtube: "youtube.com/noumanalikhan" },
  { id: "s6", slug: "omar-suleiman", name: "Omar Suleiman", designation: "Islamic Scholar", image: "/placeholder.svg?height=96&width=96", languages: ["en"], description: "Omar Suleiman is the founding president of the Yaqeen Institute for Islamic Research.", website: "yaqeeninstitute.org", facebook: "fb.com/omarsuleiman", twitter: "twitter.com/omarsuleiman", youtube: "youtube.com/omarsuleiman" },
  { id: "s7", slug: "zakir-naik", name: "Dr. Zakir Naik", designation: "Islamic Preacher", image: "/placeholder.svg?height=96&width=96", languages: ["en", "hi"], description: "Dr. Zakir Naik is an Indian Islamic preacher and public speaker.", website: "zakirnaik.com", facebook: "fb.com/zakirnaik", twitter: "twitter.com/zakirnaik", youtube: "youtube.com/zakirnaik" },
  { id: "s8", slug: "assim-al-hakeem", name: "Sheikh Assim Al Hakeem", designation: "Islamic Scholar", image: "/placeholder.svg?height=96&width=96", languages: ["en", "ar"], description: "Sheikh Assim Al Hakeem is a Saudi-based Islamic scholar and teacher.", website: "assimalhakeem.com", facebook: "fb.com/assimalhakeem", twitter: "twitter.com/assimalhakeem", youtube: "youtube.com/assimalhakeem" },
  { id: "s9", slug: "hamza-yusuf", name: "Sheikh Hamza Yusuf", designation: "Islamic Scholar", image: "/placeholder.svg?height=96&width=96", languages: ["en", "ar"], description: "Sheikh Hamza Yusuf is an American Islamic scholar and co-founder of Zaytuna College.", website: "hamzayusuf.com", facebook: "fb.com/hamzayusuf", twitter: "twitter.com/hamzayusuf", youtube: "youtube.com/hamzayusuf" },
  { id: "s10", slug: "ibn-uthaymeen", name: "Sheikh Ibn Uthaymeen", designation: "Islamic Scholar", image: "/placeholder.svg?height=96&width=96", languages: ["ar", "en"], description: "Sheikh Ibn Uthaymeen was a Saudi Islamic scholar and teacher.", website: "binothaimeen.com", facebook: "", twitter: "", youtube: "" },
];

export const mockCategories = [
  { id: "c1", slug: "aqeedah", name: "Aqeedah", description: "Islamic Belief and Creed", videoCount: 245, languages: ["en", "ar", "bn"] },
  { id: "c2", slug: "fiqh", name: "Fiqh", description: "Islamic Jurisprudence", videoCount: 189, languages: ["en", "ar", "hi"] },
  { id: "c3", slug: "hadith", name: "Hadith", description: "Prophetic Traditions", videoCount: 312, languages: ["en", "ar"] },
  { id: "c4", slug: "tafsir", name: "Tafsir", description: "Quranic Exegesis", videoCount: 278, languages: ["en", "ar", "bn"] },
  { id: "c5", slug: "seerah", name: "Seerah", description: "Prophetic Biography", videoCount: 156, languages: ["en", "ur"] },
  { id: "c6", slug: "dawah", name: "Dawah", description: "Islamic Propagation", videoCount: 198, languages: ["en", "hi"] },
  { id: "c7", slug: "family", name: "Family", description: "Marriage and Family Life", videoCount: 134, languages: ["en"] },
  { id: "c8", slug: "finance", name: "Finance", description: "Islamic Finance", videoCount: 87, languages: ["en", "ar"] },
  { id: "c9", slug: "youth", name: "Youth", description: "Youth Development", videoCount: 112, languages: ["en"] },
  { id: "c10", slug: "spirituality", name: "Spirituality", description: "Tazkiyah and Purification", videoCount: 203, languages: ["en", "ar"] },
  { id: "c11", slug: "quran", name: "Quran", description: "Quran Recitation and Memorization", videoCount: 345, languages: ["en", "ar", "bn", "hi"] },
  { id: "c12", slug: "salah", name: "Salah", description: "Prayer and Worship", videoCount: 167, languages: ["en", "hi"] },
  { id: "c13", slug: "zakat", name: "Zakat", description: "Charity and Alms", videoCount: 56, languages: ["en", "ar"] },
  { id: "c14", slug: "hajj", name: "Hajj", description: "Pilgrimage", videoCount: 78, languages: ["en", "ar"] },
  { id: "c15", slug: "fasting", name: "Fasting", description: "Sawm and Ramadan", videoCount: 145, languages: ["en", "bn"] },
];

// ----- Expanded mock videos for search (with scholar field) -----
export const mockSearchResults = [
  // === Aqeedah - Sheikh Abdul Alim - Islamic Guidance (3 videos) ===
  {
    id: "v100",
    title: "The Purpose of Life - Powerful Islamic Reminder",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "208K views",
    timeAgo: "6 days ago",
    duration: "18:28",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A powerful reminder about the true purpose of life from an Islamic perspective.",
    language: "en",
    category: "Aqeedah",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v101",
    title: "Understanding Tawheed - The Oneness of Allah",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "312K views",
    timeAgo: "3 days ago",
    duration: "22:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A detailed explanation of Tawheed and its importance in Islam.",
    language: "en",
    category: "Aqeedah",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v102",
    title: "The Six Pillars of Faith - Complete Guide",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "189K views",
    timeAgo: "1 week ago",
    duration: "28:40",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "An in-depth look at the six pillars of faith in Islam.",
    language: "en",
    category: "Aqeedah",
    scholar: "Sheikh Abdul Alim",
  },
  // === Aqeedah - Sheikh Abdul Alim - Daily Dawah (3 videos) ===
  {
    id: "v103",
    title: "The Day of Judgment - Signs and Events",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "350K views",
    timeAgo: "2 weeks ago",
    duration: "32:10",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "An in-depth look at the signs of the Day of Judgment from Islamic sources.",
    language: "en",
    category: "Aqeedah",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v104",
    title: "Belief in Allah's Attributes - A Detailed Study",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "275K views",
    timeAgo: "5 days ago",
    duration: "26:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A comprehensive study of Allah's attributes and their significance.",
    language: "en",
    category: "Aqeedah",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v105",
    title: "The Reality of Dajjal (False Messiah) - Dr. Zakir Naik",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "430K views",
    timeAgo: "3 weeks ago",
    duration: "45:00",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Dr. Zakir Naik discusses the signs and reality of the Dajjal from Islamic eschatology.",
    language: "en",
    category: "Aqeedah",
    scholar: "Sheikh Abdul Alim",
  },
  // === Tafsir - Sheikh Yasir Qadhi - Islamic Guidance (3 videos) ===
  {
    id: "v106",
    title: "Tafsir of Surah Al-Fatiha - Sheikh Yasir Qadhi",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "150K views",
    timeAgo: "3 days ago",
    duration: "25:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Complete tafsir of Surah Al-Fatiha by Sheikh Yasir Qadhi with detailed explanations.",
    language: "en",
    category: "Tafsir",
    scholar: "Sheikh Yasir Qadhi",
  },
  {
    id: "v107",
    title: "Tafsir of Surah Al-Baqarah - Part 1",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "220K views",
    timeAgo: "1 week ago",
    duration: "38:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Sheikh Yasir Qadhi explains the key themes of Surah Al-Baqarah.",
    language: "en",
    category: "Tafsir",
    scholar: "Sheikh Yasir Qadhi",
  },
  {
    id: "v108",
    title: "Tafsir of Surah Al-Baqarah - Part 2",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "180K views",
    timeAgo: "5 days ago",
    duration: "35:40",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Sheikh Yasir Qadhi continues the tafsir of Surah Al-Baqarah.",
    language: "en",
    category: "Tafsir",
    scholar: "Sheikh Yasir Qadhi",
  },
  // === Salah - Mufti Menk - Digital Mimbar (3 videos) ===
  {
    id: "v109",
    title: "How to Pray Salah - Step by Step Guide",
    channel: "Digital Mimbar",
    channelId: "ch4",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "500K views",
    timeAgo: "1 week ago",
    duration: "12:40",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Learn how to pray salah correctly with this step by step guide for beginners.",
    language: "en",
    category: "Salah",
    scholar: "Mufti Menk",
  },
  {
    id: "v110",
    title: "The Importance of Salah in Islam",
    channel: "Digital Mimbar",
    channelId: "ch4",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "340K views",
    timeAgo: "2 weeks ago",
    duration: "18:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Mufti Menk explains the significance of Salah in the life of a Muslim.",
    language: "en",
    category: "Salah",
    scholar: "Mufti Menk",
  },
  {
    id: "v111",
    title: "Common Mistakes in Prayer - How to Correct Them",
    channel: "Digital Mimbar",
    channelId: "ch4",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "290K views",
    timeAgo: "4 days ago",
    duration: "22:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A guide to common mistakes in Salah and how to fix them.",
    language: "en",
    category: "Salah",
    scholar: "Mufti Menk",
  },
  // === Family - Mufti Menk - Merciful Servant (3 videos) ===
  {
    id: "v112",
    title: "Marriage in Islam - Rights and Responsibilities",
    channel: "Merciful Servant",
    channelId: "ch3",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "220K views",
    timeAgo: "1 week ago",
    duration: "22:05",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "An essential guide to marriage in Islam covering rights, responsibilities, and love.",
    language: "en",
    category: "Family",
    scholar: "Mufti Menk",
  },
  {
    id: "v113",
    title: "Parenting in Islam - Raising Righteous Children",
    channel: "Merciful Servant",
    channelId: "ch3",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "180K views",
    timeAgo: "2 weeks ago",
    duration: "28:45",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Islamic principles for parenting and raising children who are mindful of Allah.",
    language: "en",
    category: "Family",
    scholar: "Mufti Menk",
  },
  {
    id: "v114",
    title: "Family Values in Islam - A Complete Guide",
    channel: "Merciful Servant",
    channelId: "ch3",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "150K views",
    timeAgo: "3 weeks ago",
    duration: "25:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A comprehensive guide to family values and relationships in Islam.",
    language: "en",
    category: "Family",
    scholar: "Mufti Menk",
  },
  // === Seerah - Sheikh Hamza Yusuf - One Islam Productions (3 videos) ===
  {
    id: "v115",
    title: "The Life of Prophet Muhammad (Seerah) - Part 1",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "310K views",
    timeAgo: "2 months ago",
    duration: "38:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "The first part of a comprehensive series on the life of Prophet Muhammad (peace be upon him).",
    language: "en",
    category: "Seerah",
    scholar: "Sheikh Hamza Yusuf",
  },
  {
    id: "v116",
    title: "Seerah of Prophet Muhammad (Part 2) - Sheikh Hamza Yusuf",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "215K views",
    timeAgo: "1 month ago",
    duration: "43:10",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Part 2 of the Seerah series covering the early Meccan period.",
    language: "en",
    category: "Seerah",
    scholar: "Sheikh Hamza Yusuf",
  },
  {
    id: "v117",
    title: "The Seerah of Prophet Muhammad - Part 3",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "190K views",
    timeAgo: "3 weeks ago",
    duration: "40:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Part 3 of the Seerah series covering the Medinan period.",
    language: "en",
    category: "Seerah",
    scholar: "Sheikh Hamza Yusuf",
  },
  // === Zakat - Dr. Bilal Philips - Islam Channel (3 videos) ===
  {
    id: "v118",
    title: "Zakat: The Third Pillar of Islam",
    channel: "Islam Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "145K views",
    timeAgo: "5 days ago",
    duration: "14:50",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A detailed explanation of Zakat, its calculation, and importance in Islam.",
    language: "en",
    category: "Zakat",
    scholar: "Dr. Bilal Philips",
  },
  {
    id: "v119",
    title: "Zakat Al-Fitr - Rules and Calculation",
    channel: "Islam Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "98K views",
    timeAgo: "1 week ago",
    duration: "12:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A detailed explanation of Zakat Al-Fitr and how to calculate it.",
    language: "en",
    category: "Zakat",
    scholar: "Dr. Bilal Philips",
  },
  {
    id: "v120",
    title: "Zakat on Wealth - A Comprehensive Guide",
    channel: "Islam Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "120K views",
    timeAgo: "2 weeks ago",
    duration: "18:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A complete guide to calculating Zakat on wealth and assets.",
    language: "en",
    category: "Zakat",
    scholar: "Dr. Bilal Philips",
  },
  // === Spirituality - Nouman Ali Khan - Daily Dawah (3 videos) ===
  {
    id: "v121",
    title: "How to Increase Your Faith (Iman) - Nouman Ali Khan",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "275K views",
    timeAgo: "2 weeks ago",
    duration: "19:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Nouman Ali Khan shares practical tips to strengthen your faith in everyday life.",
    language: "en",
    category: "Spirituality",
    scholar: "Nouman Ali Khan",
  },
  {
    id: "v122",
    title: "The Power of Dhikr - Nouman Ali Khan",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "210K views",
    timeAgo: "1 week ago",
    duration: "16:50",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Nouman Ali Khan explores the spiritual power of dhikr and its impact on the heart.",
    language: "en",
    category: "Spirituality",
    scholar: "Nouman Ali Khan",
  },
  {
    id: "v123",
    title: "Connecting with Allah - A Spiritual Guide",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "190K views",
    timeAgo: "3 weeks ago",
    duration: "21:40",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A spiritual guide to deepening your connection with Allah.",
    language: "en",
    category: "Spirituality",
    scholar: "Nouman Ali Khan",
  },
  // === Dawah - Mufti Menk - The Deen Show (3 videos) ===
  {
    id: "v124",
    title: "The Power of Dawah - Mufti Menk",
    channel: "The Deen Show",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "320K views",
    timeAgo: "2 weeks ago",
    duration: "24:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Mufti Menk discusses the importance and power of Dawah in Islam.",
    language: "en",
    category: "Dawah",
    scholar: "Mufti Menk",
  },
  {
    id: "v125",
    title: "Effective Dawah - Strategies and Tips",
    channel: "The Deen Show",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "180K views",
    timeAgo: "1 week ago",
    duration: "20:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Practical strategies and tips for effective Dawah.",
    language: "en",
    category: "Dawah",
    scholar: "Mufti Menk",
  },
  {
    id: "v126",
    title: "Dawah in the Modern World - Challenges and Opportunities",
    channel: "The Deen Show",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "150K views",
    timeAgo: "3 weeks ago",
    duration: "26:45",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Discussing the challenges and opportunities of Dawah in the modern world.",
    language: "en",
    category: "Dawah",
    scholar: "Mufti Menk",
  },
  // === Fiqh - Sheikh Assim Al Hakeem - Islamic Guidance (3 videos) ===
  {
    id: "v127",
    title: "Fiqh of Prayer - Sheikh Assim Al Hakeem",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "190K views",
    timeAgo: "1 week ago",
    duration: "34:12",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Sheikh Assim Al Hakeem explains the fiqh rulings related to prayer in detail.",
    language: "en",
    category: "Fiqh",
    scholar: "Sheikh Assim Al Hakeem",
  },
  {
    id: "v128",
    title: "Fiqh of Fasting - Complete Guide",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "160K views",
    timeAgo: "2 weeks ago",
    duration: "28:45",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A comprehensive guide to the fiqh of fasting in Islam.",
    language: "en",
    category: "Fiqh",
    scholar: "Sheikh Assim Al Hakeem",
  },
  {
    id: "v129",
    title: "Fiqh of Zakat - A Detailed Study",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "140K views",
    timeAgo: "3 weeks ago",
    duration: "30:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A detailed study of the fiqh of Zakat in Islam.",
    language: "en",
    category: "Fiqh",
    scholar: "Sheikh Assim Al Hakeem",
  },
  // === Quran - Sheikh Abdul Alim - Eman Channel (3 videos) ===
  {
    id: "v130",
    title: "Quran Recitation with English Translation - Surah Al-Fatiha",
    channel: "Eman Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "88K views",
    timeAgo: "2 days ago",
    duration: "4:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Beautiful recitation of Surah Al-Fatiha with English translation and explanation.",
    language: "en",
    category: "Quran",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v131",
    title: "Quran Recitation - Surah Al-Baqarah (Full)",
    channel: "Eman Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "200K views",
    timeAgo: "1 week ago",
    duration: "2:15:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Full recitation of Surah Al-Baqarah with English translation.",
    language: "en",
    category: "Quran",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v132",
    title: "Surah Al-Kahf - Reflection and Lessons",
    channel: "Eman Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "320K views",
    timeAgo: "2 weeks ago",
    duration: "28:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A deep reflection on Surah Al-Kahf and its lessons for modern times.",
    language: "en",
    category: "Quran",
    scholar: "Sheikh Abdul Alim",
  },
  // === Fasting - Sheikh Assim Al Hakeem - Huda TV (3 videos) ===
  {
    id: "v133",
    title: "Fasting in Islam - A Complete Guide",
    channel: "Huda TV",
    channelId: "ch5",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "95K views",
    timeAgo: "4 days ago",
    duration: "22:30",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A complete guide to fasting in Islam, including rules and benefits.",
    language: "en",
    category: "Fasting",
    scholar: "Sheikh Assim Al Hakeem",
  },
  {
    id: "v134",
    title: "Ramadan Preparation Guide - Complete Plan",
    channel: "Huda TV",
    channelId: "ch5",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "300K views",
    timeAgo: "2 weeks ago",
    duration: "20:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A complete guide to preparing for Ramadan, including spiritual and practical tips.",
    language: "en",
    category: "Fasting",
    scholar: "Sheikh Assim Al Hakeem",
  },
  {
    id: "v135",
    title: "The Virtues of Ramadan and Fasting",
    channel: "Huda TV",
    channelId: "ch5",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "210K views",
    timeAgo: "1 week ago",
    duration: "18:45",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "Exploring the virtues of Ramadan and the blessings of fasting.",
    language: "en",
    category: "Fasting",
    scholar: "Sheikh Assim Al Hakeem",
  },
  // === Hajj - Sheikh Hamza Yusuf - One Islam Productions (3 videos) ===
  {
    id: "v136",
    title: "Hajj and Umrah - A Step by Step Guide",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "180K views",
    timeAgo: "1 month ago",
    duration: "35:40",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A detailed guide to performing Hajj and Umrah according to the Sunnah.",
    language: "en",
    category: "Hajj",
    scholar: "Sheikh Hamza Yusuf",
  },
  {
    id: "v137",
    title: "The Spiritual Significance of Hajj",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "130K views",
    timeAgo: "3 weeks ago",
    duration: "26:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "A reflection on the spiritual significance of Hajj in Islam.",
    language: "en",
    category: "Hajj",
    scholar: "Sheikh Hamza Yusuf",
  },
  {
    id: "v138",
    title: "The Story of Hajj - From Abraham to Today",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "160K views",
    timeAgo: "2 weeks ago",
    duration: "32:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "The historical and spiritual story of Hajj from Prophet Abraham to today.",
    language: "en",
    category: "Hajj",
    scholar: "Sheikh Hamza Yusuf",
  },
  // === Arabic Language Videos ===
  {
    id: "v139",
    title: "تفسير سورة الفاتحة - شرح مبسط",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "95K views",
    timeAgo: "1 week ago",
    duration: "22:10",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "تفسير سورة الفاتحة باللغة العربية بأسلوب مبسط",
    language: "ar",
    category: "Tafsir",
    scholar: "Sheikh Ibn Uthaymeen",
  },
  {
    id: "v140",
    title: "سيرة النبي محمد - الجزء الأول",
    channel: "Islam Channel",
    channelId: "ch8",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "120K views",
    timeAgo: "2 weeks ago",
    duration: "40:35",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "سلسلة السيرة النبوية بدءاً من ميلاد النبي محمد (صلى الله عليه وسلم)",
    language: "ar",
    category: "Seerah",
    scholar: "Sheikh Hamza Yusuf",
  },
  {
    id: "v141",
    title: "أحكام الزكاة في الإسلام - الشيخ ابن عثيمين",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "78K views",
    timeAgo: "4 days ago",
    duration: "26:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "شرح مفصل لأحكام الزكاة في الإسلام من كلام الشيخ ابن عثيمين",
    language: "ar",
    category: "Zakat",
    scholar: "Sheikh Ibn Uthaymeen",
  },
  // === Hindi Language Videos ===
  {
    id: "v142",
    title: "इस्लाम में तौहीद (एकेश्वरवाद) का महत्व",
    channel: "Digital Mimbar",
    channelId: "ch4",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "45K views",
    timeAgo: "3 days ago",
    duration: "15:40",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "इस्लाम में तौहीद (एकेश्वरवाद) के महत्व को समझाते हैं।",
    language: "hi",
    category: "Aqeedah",
    scholar: "Dr. Zakir Naik",
  },
  {
    id: "v143",
    title: "कुरान की तिलावत - सूरह यासीन हिंदी अनुवाद के साथ",
    channel: "Huda TV",
    channelId: "ch5",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "30K views",
    timeAgo: "1 week ago",
    duration: "8:50",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "सूरह यासीन की तिलावत हिंदी अनुवाद और सरल व्याख्या के साथ।",
    language: "hi",
    category: "Quran",
    scholar: "Nouman Ali Khan",
  },
  // === Bengali Language Videos ===
  {
    id: "v144",
    title: "ইসলামে নামাজের গুরুত্ব - শেখ আব্দুল আলীম",
    channel: "Daily Dawah",
    channelId: "ch2",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "55K views",
    timeAgo: "5 days ago",
    duration: "18:20",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "ইসলামে নামাজের গুরুত্ব এবং তার পদ্ধতি সম্পর্কে বিস্তারিত আলোচনা।",
    language: "bn",
    category: "Salah",
    scholar: "Sheikh Abdul Alim",
  },
  {
    id: "v145",
    title: "পবিত্র কুরআন তিলাওয়াত - সূরা ফাতিহা বাংলা অনুবাদ",
    channel: "One Islam Productions",
    channelId: "ch7",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "28K views",
    timeAgo: "2 days ago",
    duration: "5:10",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "সূরা ফাতিহার তিলাওয়াত ও বাংলা অনুবাদ ও তাফসীর।",
    language: "bn",
    category: "Quran",
    scholar: "Sheikh Abdul Alim",
  },
  // === Urdu Language Videos ===
  {
    id: "v146",
    title: "توحید کا مفہوم - شیخ یاسر قاضی",
    channel: "Islamic Guidance",
    channelId: "ch1",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "67K views",
    timeAgo: "1 week ago",
    duration: "20:15",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "شیخ یاسر قاضی توحید کے مفہوم کو آسان طریقے سے بیان کرتے ہیں۔",
    language: "ur",
    category: "Aqeedah",
    scholar: "Sheikh Yasir Qadhi",
  },
  {
    id: "v147",
    title: "قرآن مجید کی تلاوت - سورہ بقرہ اردو ترجمہ",
    channel: "Peace TV",
    channelId: "ch6",
    channelAvatar: "/placeholder.svg?height=36&width=36",
    views: "40K views",
    timeAgo: "4 days ago",
    duration: "12:45",
    thumbnail: "/placeholder.svg?height=480&width=854",
    description: "سورہ بقرہ کی تلاوت اردو ترجمہ اور مختصر تفسیر۔",
    language: "ur",
    category: "Quran",
    scholar: "Dr. Zakir Naik",
  },
];

// Keep existing mock data for other parts of the app
export const mockVideos = [
  { id: "v1", title: "The Purpose of Life - Powerful Islamic Reminder", channelId: "ch2", channel: "Daily Dawah", channelAvatar: "/placeholder.svg?height=36&width=36", views: "208K views", timeAgo: "6 days ago", duration: "18:28", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Dawah", description: "A powerful reminder about the true purpose of life from an Islamic perspective." },
  { id: "v2", title: "Tafsir of Surah Al-Fatiha - Sheikh Yasir Qadhi", channelId: "ch1", channel: "Islamic Guidance", channelAvatar: "/placeholder.svg?height=36&width=36", views: "150K views", timeAgo: "3 days ago", duration: "25:15", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Tafsir", description: "Complete tafsir of Surah Al-Fatiha by Sheikh Yasir Qadhi." },
  { id: "v3", title: "How to Pray Salah - Step by Step Guide for Beginners", channelId: "ch4", channel: "Digital Mimbar", channelAvatar: "/placeholder.svg?height=36&width=36", views: "500K views", timeAgo: "1 week ago", duration: "12:40", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Salah", description: "Learn how to pray salah correctly with this step by step guide." },
  { id: "v4", title: "The Day of Judgment - Signs and Events", channelId: "ch6", channel: "Peace TV", channelAvatar: "/placeholder.svg?height=36&width=36", views: "350K views", timeAgo: "2 weeks ago", duration: "32:10", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Aqeedah", description: "An in-depth look at the signs of the Day of Judgment." },
  { id: "v5", title: "Powerful Dua for Protection and Guidance", channelId: "ch5", channel: "Huda TV", channelAvatar: "/placeholder.svg?height=36&width=36", views: "420K views", timeAgo: "1 month ago", duration: "8:45", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Spirituality", description: "A collection of powerful duas for protection and guidance." },
  { id: "v6", title: "Islamic Morning Routine - Start Your Day Right", channelId: "ch2", channel: "Daily Dawah", channelAvatar: "/placeholder.svg?height=36&width=36", views: "180K views", timeAgo: "3 weeks ago", duration: "10:30", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Dawah", description: "Start your day with these Islamic morning practices." },
  { id: "v7", title: "Understanding Surah Al-Baqarah - Dr. Bilal Philips", channelId: "ch1", channel: "Islamic Guidance", channelAvatar: "/placeholder.svg?height=36&width=36", views: "98K views", timeAgo: "4 days ago", duration: "42:18", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Tafsir", description: "Dr. Bilal Philips explains the key themes of Surah Al-Baqarah." },
  { id: "v8", title: "Marriage in Islam - Rights and Responsibilities", channelId: "ch3", channel: "Merciful Servant", channelAvatar: "/placeholder.svg?height=36&width=36", views: "220K views", timeAgo: "1 week ago", duration: "22:05", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Family", description: "An essential guide to marriage in Islam covering rights, responsibilities, and love." },
  { id: "v9", title: "The Life of Prophet Muhammad (Seerah) - Part 1", channelId: "ch7", channel: "One Islam Productions", channelAvatar: "/placeholder.svg?height=36&width=36", views: "310K views", timeAgo: "2 months ago", duration: "38:20", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Seerah", description: "The first part of a comprehensive series on the life of Prophet Muhammad (peace be upon him)." },
  { id: "v10", title: "Zakat: The Third Pillar of Islam", channelId: "ch7", channel: "One Islam Productions", channelAvatar: "/placeholder.svg?height=36&width=36", views: "145K views", timeAgo: "5 days ago", duration: "14:50", thumbnail: "/placeholder.svg?height=480&width=854", language: "en", category: "Zakat", description: "A detailed explanation of Zakat, its calculation, and importance in Islam." },
  { id: "v11", title: "تفسير سورة الفاتحة - شرح مبسط", channelId: "ch1", channel: "Islamic Guidance", channelAvatar: "/placeholder.svg?height=36&width=36", views: "95K views", timeAgo: "1 week ago", duration: "22:10", thumbnail: "/placeholder.svg?height=480&width=854", language: "ar", category: "Tafsir", description: "تفسير سورة الفاتحة باللغة العربية بأسلوب مبسط" },
  { id: "v12", title: "سيرة النبي محمد - الجزء الأول", channelId: "ch7", channel: "One Islam Productions", channelAvatar: "/placeholder.svg?height=36&width=36", views: "120K views", timeAgo: "2 weeks ago", duration: "40:35", thumbnail: "/placeholder.svg?height=480&width=854", language: "ar", category: "Seerah", description: "سلسلة السيرة النبوية بدءاً من ميلاد النبي محمد (صلى الله عليه وسلم)" },
  { id: "v13", title: "ইসলামে নামাজের গুরুত্ব - শেখ আব্দুল আলীম", channelId: "ch2", channel: "Daily Dawah", channelAvatar: "/placeholder.svg?height=36&width=36", views: "55K views", timeAgo: "5 days ago", duration: "18:20", thumbnail: "/placeholder.svg?height=480&width=854", language: "bn", category: "Salah", description: "ইসলামে নামাজের গুরুত্ব এবং তার পদ্ধতি সম্পর্কে বিস্তারিত আলোচনা।" },
  { id: "v14", title: "পবিত্র কুরআন তিলাওয়াত - সূরা ফাতিহা বাংলা অনুবাদ", channelId: "ch7", channel: "One Islam Productions", channelAvatar: "/placeholder.svg?height=36&width=36", views: "28K views", timeAgo: "2 days ago", duration: "5:10", thumbnail: "/placeholder.svg?height=480&width=854", language: "bn", category: "Quran", description: "সূরা ফাতিহার তিলাওয়াত ও বাংলা অনুবাদ ও তাফসীর।" },
  { id: "v15", title: "इस्लाम में तौहीद (एकेश्वरवाद) का महत्व", channelId: "ch4", channel: "Digital Mimbar", channelAvatar: "/placeholder.svg?height=36&width=36", views: "45K views", timeAgo: "3 days ago", duration: "15:40", thumbnail: "/placeholder.svg?height=480&width=854", language: "hi", category: "Aqeedah", description: "इस्लाम में तौहीद (एकेश्वरवाद) के महत्व को समझाते हैं।" },
];

export const mockPlaylists = [
  { id: "p1", slug: "quran-tafsir-series", name: "Quran Tafsir Series", videoIds: ["v2", "v7"], updatedAt: "Updated 2 days ago", isPublic: true },
  { id: "p2", slug: "daily-reminders", name: "Daily Reminders", videoIds: ["v1", "v6"], updatedAt: "Updated 5 days ago", isPublic: true },
  { id: "p3", slug: "salah-guide", name: "Salah Guide", videoIds: ["v3"], updatedAt: "Updated 1 week ago", isPublic: false },
];

export const mockWatchLater = [
  { id: "v1", title: "The Purpose of Life - Powerful Islamic Reminder", channel: "Daily Dawah", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "208K views", timeAgo: "6 days ago", duration: "18:28" },
  { id: "v5", title: "Powerful Dua for Protection and Guidance", channel: "Huda TV", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "420K views", timeAgo: "1 month ago", duration: "8:45" },
];

export const mockLikedVideos = [
  { id: "v2", title: "Tafsir of Surah Al-Fatiha - Sheikh Yasir Qadhi", channel: "Islamic Guidance", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "150K views", timeAgo: "3 days ago", duration: "25:15" },
  { id: "v3", title: "How to Pray Salah - Step by Step Guide for Beginners", channel: "Digital Mimbar", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "500K views", timeAgo: "1 week ago", duration: "12:40" },
];

export const mockHistory = [
  { id: "v1", title: "The Purpose of Life - Powerful Islamic Reminder", channel: "Daily Dawah", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "208K views", timeAgo: "2 hours ago", duration: "18:28", watchedPercent: 75 },
  { id: "v2", title: "Tafsir of Surah Al-Fatiha - Sheikh Yasir Qadhi", channel: "Islamic Guidance", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "150K views", timeAgo: "Yesterday", duration: "25:15", watchedPercent: 100 },
  { id: "v3", title: "How to Pray Salah - Step by Step Guide for Beginners", channel: "Digital Mimbar", channelAvatar: "/placeholder.svg?height=36&width=36", thumbnail: "/placeholder.svg?height=480&width=854", views: "500K views", timeAgo: "3 days ago", duration: "12:40", watchedPercent: 45 },
];

export const mockComments = [
  { id: "c1", user: "Ahmad Khan", avatar: "/placeholder.svg?height=32&width=32", timeAgo: "2 days ago", content: "MashaAllah, very beneficial lecture! May Allah bless you.", likes: 245, dislikes: 12 },
  { id: "c2", user: "Fatima Hassan", avatar: "/placeholder.svg?height=32&width=32", timeAgo: "1 week ago", content: "Beautiful reminder. SubhanAllah!", likes: 567, dislikes: 23 },
  { id: "c3", user: "Omar Farooq", avatar: "/placeholder.svg?height=32&width=32", timeAgo: "3 days ago", content: "This changed my perspective. JazakAllah khair!", likes: 189, dislikes: 8 },
];

export const mockShorts = [
  { id: "s1", title: "Surah Al Baqarah - Beautiful Recitation", channel: "Islamic Recitation", channelAvatar: "/placeholder.svg?height=36&width=36", likes: "15K", comments: "1.2K", thumbnail: "/placeholder.svg?height=480&width=270", duration: "0:58" },
  { id: "s2", title: "Powerful Reminder - Don't Lose Hope", channel: "Daily Dawah", channelAvatar: "/placeholder.svg?height=36&width=36", likes: "25K", comments: "2.1K", thumbnail: "/placeholder.svg?height=480&width=270", duration: "0:45" },
  { id: "s3", title: "Beautiful Adhan - Masjid Al-Haram", channel: "Islamic Sounds", channelAvatar: "/placeholder.svg?height=36&width=36", likes: "50K", comments: "3.5K", thumbnail: "/placeholder.svg?height=480&width=270", duration: "1:02" },
];

export const mockAccounts = [
  { id: "acc1", name: "Abdullah Rahman", email: "abdullah@example.com", avatar: "", initials: "AR" },
  { id: "acc2", name: "Fatima Begum", email: "fatima@example.com", avatar: "", initials: "FB" },
  { id: "acc3", name: "Guest User", email: "guest@deeni.tube", avatar: "", initials: "GU" },
];